[package]
name = "agentmesh"
description = "The service mesh for AI tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "agentmesh"
path = "src/main.rs"

[dependencies]
agentmesh-config = { path = "../agentmesh-config", version = "0.3.1" }
agentmesh-control-api = { path = "../agentmesh-control-api", version = "0.3.1" }
agentmesh-control-plane = { path = "../agentmesh-control-plane", version = "0.3.1" }
agentmesh-gateway = { path = "../agentmesh-gateway", version = "0.3.1" }
agentmesh-proxy = { path = "../agentmesh-proxy", version = "0.3.1" }
agentmesh-storage = { path = "../agentmesh-storage", version = "0.3.1" }
agentmesh-teach = { path = "../agentmesh-teach", version = "0.3.1" }
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
